language: r
cache: packages
r:
    - bioc-release

matrix:
    include:
        - os: linux
          dist: trusty
          apt:
            sources:
                - debian-sid
            packages:
                - libfreetype6
        - os: osx
          osx_image: xcode7.3
          brew_packages: cairo
          latex: false
    exclude:
        - dist: precise

r_github_packages:
    - jimhester/covr

after_success:
    - Rscript -e 'library(covr);codecov()'

notifications:
    email: false
